server:
  port: 8080  # API Gateway runs on port 8080

spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379  # Redis should be running locally

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: book-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/books/**

jwt:
  secret: my-super-secret-key
  expiration: 3600000  # 1 hour in milliseconds
